AllCops:
  Excludes:
    - db/schema.rb
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IndentationConsistency:
  EnforcedStyle: rails
